version: '3.8'
services:

  postgresql_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=repo_tutorial
      - POSTGRES_PASSWORD=rqPbqi4cRPP3JQDa
      - POSTGRES_MULTIPLE_DATABASES=repo_test
    ports:
      - '5432:5432'
    volumes:
      - ./Postgresql/Volume:/var/lib/postresql/data
      - ./Postgresql/:/docker-entrypoint-initdb.d